//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.29 at 02:46:09 PM IRST 
//


package com.hotelapp.xml.room;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.hotelapp.xml.room package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.hotelapp.xml.room
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteRoomRequest }
     * 
     */
    public DeleteRoomRequest createDeleteRoomRequest() {
        return new DeleteRoomRequest();
    }

    /**
     * Create an instance of {@link CreateRoomResponse }
     * 
     */
    public CreateRoomResponse createCreateRoomResponse() {
        return new CreateRoomResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link GetAllStringIdRoomsRequest }
     * 
     */
    public GetAllStringIdRoomsRequest createGetAllStringIdRoomsRequest() {
        return new GetAllStringIdRoomsRequest();
    }

    /**
     * Create an instance of {@link GetAllStringIdRoomsResponse }
     * 
     */
    public GetAllStringIdRoomsResponse createGetAllStringIdRoomsResponse() {
        return new GetAllStringIdRoomsResponse();
    }

    /**
     * Create an instance of {@link IsRoomAvailableRequest }
     * 
     */
    public IsRoomAvailableRequest createIsRoomAvailableRequest() {
        return new IsRoomAvailableRequest();
    }

    /**
     * Create an instance of {@link CreateRoomRequest }
     * 
     */
    public CreateRoomRequest createCreateRoomRequest() {
        return new CreateRoomRequest();
    }

    /**
     * Create an instance of {@link UpdateRoomResponse }
     * 
     */
    public UpdateRoomResponse createUpdateRoomResponse() {
        return new UpdateRoomResponse();
    }

    /**
     * Create an instance of {@link CreateBookResponse }
     * 
     */
    public CreateBookResponse createCreateBookResponse() {
        return new CreateBookResponse();
    }

    /**
     * Create an instance of {@link DeleteRoomResponse }
     * 
     */
    public DeleteRoomResponse createDeleteRoomResponse() {
        return new DeleteRoomResponse();
    }

    /**
     * Create an instance of {@link IsRoomAvailableResponse }
     * 
     */
    public IsRoomAvailableResponse createIsRoomAvailableResponse() {
        return new IsRoomAvailableResponse();
    }

    /**
     * Create an instance of {@link CreateBookRequest }
     * 
     */
    public CreateBookRequest createCreateBookRequest() {
        return new CreateBookRequest();
    }

    /**
     * Create an instance of {@link UpdateRoomRequest }
     * 
     */
    public UpdateRoomRequest createUpdateRoomRequest() {
        return new UpdateRoomRequest();
    }

}
