//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.29 at 02:46:09 PM IRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hotelapp.com/xml/room", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.hotelapp.xml.room;
